"""Load and join the two upstream data files needed by Logreg.

Data dependencies:
  - patient_timelines.json  — from `python -m Preprocess.run_pipeline`
                              Each record has subject_id, hadm_id, discharge_summary, events, ...
  - QA pairs (choose one):
      data/generated/qa_pairs.json
          Generated by `python -m Generation.generate_qa` using gpt-4o on the full
          patient record. Includes source_types per pair. Questions requiring only
          structured events (no discharge_summary in source_types) are filtered out
          because weak supervision cannot label discharge chunks for them.
      data/physionet.org/files/ehr-ds-qa/1.0.0/mimic_iv_note_qa.json
          The EHR-DS-QA dataset (shipped in repo). Generated from discharge summaries
          only — answers are always in the discharge text, so weak supervision is
          always valid. No source_types field; all pairs are kept.

Pass the desired QA path explicitly to load_qa_pairs() or load_and_merge().
No BigQuery or network calls happen here. All data loading is local file I/O.
"""

from __future__ import annotations

import json
from pathlib import Path

# ── Known QA sources (pass either to load_qa_pairs / load_and_merge) ─────────
QA_GENERATED = Path("data/generated/qa_pairs.json")
QA_EHR_DS_QA = Path("data/physionet.org/files/ehr-ds-qa/1.0.0/mimic_iv_note_qa.json")

_DEFAULT_TIMELINES = Path("data/processed/patient_timelines.json")
_DEFAULT_QA_JSON   = QA_GENERATED


def load_timelines(path: str | Path = _DEFAULT_TIMELINES) -> list[dict]:
    """Load patient_timelines.json written by Preprocess.run_pipeline.

    Each record contains at minimum:
        subject_id        int
        hadm_id           int
        discharge_summary str   (full discharge note text from MIMIC-IV-Note via BigQuery)
        events            list  (temporally sorted structured clinical events)
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"Patient timelines not found at '{path}'.\n"
            "Run the preprocessing pipeline first:\n"
            "  python -m Preprocess.run_pipeline --format json"
        )
    with path.open() as f:
        return json.load(f)


def load_qa_pairs(path: str | Path = _DEFAULT_QA_JSON) -> list[dict]:
    """Load a QA pairs file.

    Pass QA_GENERATED or QA_EHR_DS_QA (or any custom path) explicitly to choose
    which dataset to use.  Defaults to QA_GENERATED (data/generated/qa_pairs.json).

    QA_GENERATED records contain:
        subject_id  int / str
        hadm_id     int / str
        qa_pairs    list of {question, answer, difficulty, source_types, reasoning}

    QA_EHR_DS_QA records contain:
        subject_id  int / str
        hadm_id     int / str
        qa_pairs    list of {question, answer}   (no source_types — always discharge-grounded)
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"QA pairs not found at '{path}'.\n"
            "Options:\n"
            f"  Generated (gpt-4o):  pass QA_GENERATED  — run `python -m Generation.generate_qa` first\n"
            f"  EHR-DS-QA (shipped): pass QA_EHR_DS_QA  — available at {QA_EHR_DS_QA}"
        )
    with path.open() as f:
        return json.load(f)


def _is_discharge_grounded(qa: dict) -> bool:
    """Return True if this QA pair can be answered from the discharge summary.

    Generated QA pairs (from Generation.generate_qa) include a `source_types`
    list. We only keep pairs where "discharge_summary" is one of the sources,
    because weak supervision (labeling chunks via token overlap with the answer)
    only works when the answer text appears somewhere in the discharge note.

    EHR-DS-QA pairs have no source_types field — they are always discharge-grounded
    by construction, so we keep all of them.
    """
    source_types = qa.get("source_types")
    if source_types is None:
        return True  # EHR-DS-QA: no field means always discharge-grounded
    return "discharge_summary" in source_types


def merge(
    timelines: list[dict],
    qa_records: list[dict],
) -> list[dict]:
    """Join timelines with QA pairs on (subject_id, hadm_id).

    Only retains QA pairs that are answerable from the discharge summary text
    (i.e., source_types includes "discharge_summary", or no source_types field).
    Cross-source-only questions (answers live in structured events, not in the
    discharge note) are dropped because weak supervision cannot label their chunks.

    Returns a list of dicts, one per matched admission:
        subject_id       int
        hadm_id          int
        note_text        str   — discharge_summary from the timeline
        qa_pairs         list  — [{question, answer, ...}, ...] (discharge-grounded only)
    """
    # Index QA records by (subject_id, hadm_id), filtering to discharge-grounded pairs
    qa_index: dict[tuple[int, int], list[dict]] = {}
    dropped_cross_source = 0
    for rec in qa_records:
        key = (int(rec["subject_id"]), int(rec["hadm_id"]))
        all_pairs = rec.get("qa_pairs") or []
        pairs = [
            qa for qa in all_pairs
            if qa.get("question") and qa.get("answer") and _is_discharge_grounded(qa)
        ]
        dropped_cross_source += len(all_pairs) - len(pairs)
        if pairs:
            qa_index[key] = pairs

    if dropped_cross_source > 0:
        print(
            f"Filtered out {dropped_cross_source} cross-source QA pairs "
            "(answers not in discharge summary — weak supervision inapplicable)"
        )

    merged: list[dict] = []
    skipped_no_qa   = 0
    skipped_no_note = 0

    for t in timelines:
        key = (int(t["subject_id"]), int(t["hadm_id"]))
        qa_pairs  = qa_index.get(key)
        note_text = (t.get("discharge_summary") or "").strip()

        if not qa_pairs:
            skipped_no_qa += 1
            continue
        if not note_text:
            skipped_no_note += 1
            continue

        merged.append({
            "subject_id": int(t["subject_id"]),
            "hadm_id":    int(t["hadm_id"]),
            "note_text":  note_text,
            "qa_pairs":   qa_pairs,
        })

    print(
        f"Merged {len(merged)} records "
        f"(skipped {skipped_no_qa} with no QA, {skipped_no_note} with no note text)"
    )
    return merged


def load_and_merge(
    timelines_path: str | Path = _DEFAULT_TIMELINES,
    qa_path:        str | Path = _DEFAULT_QA_JSON,
) -> list[dict]:
    """Convenience wrapper: load both files and merge in one call."""
    timelines  = load_timelines(timelines_path)
    qa_records = load_qa_pairs(qa_path)
    return merge(timelines, qa_records)
