"""Load and join the two upstream data files needed by Logreg.

Data dependencies:
  - patient_timelines.json  — from `python -m Preprocess.run_pipeline`
                              Each record has subject_id, hadm_id, discharge_summary, events, ...
  - QA pairs (choose one):
      data/generated/qa_pairs.json
          Generated by `python -m Generation.generate_qa` using gpt-4o on the full
          patient record (discharge summary + structured events). Includes source_types
          per pair.
      data/physionet.org/files/ehr-ds-qa/1.0.0/mimic_iv_note_qa.json
          The EHR-DS-QA dataset (shipped in repo). Generated from discharge summaries
          only. No source_types field.

By default, note_text is the discharge summary concatenated with serialized
structured events (labs, meds, vitals, procedures, diagnoses).  This ensures
that gpt-4o generated answers — which reference specific event values — appear
in the text that gets chunked, enabling weak supervision via token overlap.


Pass include_events=False to use only the discharge summary (original behavior).

No BigQuery or network calls happen here. All data loading is local file I/O.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

# ── Known QA sources (pass either to load_qa_pairs / load_and_merge) ─────────
QA_GENERATED = Path("data/generated/qa_pairs.json")
QA_EHR_DS_QA = Path("data/physionet.org/files/ehr-ds-qa/1.0.0/mimic_iv_note_qa.json")

_DEFAULT_TIMELINES = Path("data/processed/patient_timelines.json")
_DEFAULT_QA_JSON   = QA_GENERATED


def load_timelines(path: str | Path = _DEFAULT_TIMELINES) -> list[dict]:
    """Load patient_timelines.json written by Preprocess.run_pipeline.

    Each record contains at minimum:
        subject_id        int
        hadm_id           int
        discharge_summary str   (full discharge note text from MIMIC-IV-Note via BigQuery)
        events            list  (temporally sorted structured clinical events)
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"Patient timelines not found at '{path}'.\n"
            "Run the preprocessing pipeline first:\n"
            "  python -m Preprocess.run_pipeline --format json"
        )
    with path.open() as f:
        return json.load(f)


def load_qa_pairs(path: str | Path = _DEFAULT_QA_JSON) -> list[dict]:
    """Load a QA pairs file.

    Pass QA_GENERATED or QA_EHR_DS_QA (or any custom path) explicitly to choose
    which dataset to use.  Defaults to QA_GENERATED (data/generated/qa_pairs.json).

    QA_GENERATED records contain:
        subject_id  int / str
        hadm_id     int / str
        qa_pairs    list of {question, answer, difficulty, source_types, reasoning}

    QA_EHR_DS_QA records contain:
        subject_id  int / str
        hadm_id     int / str
        qa_pairs    list of {question, answer}   (no source_types — always discharge-grounded)
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"QA pairs not found at '{path}'.\n"
            "Options:\n"
            f"  Generated (gpt-4o):  pass QA_GENERATED  — run `python -m Generation.generate_qa` first\n"
            f"  EHR-DS-QA (shipped): pass QA_EHR_DS_QA  — available at {QA_EHR_DS_QA}"
        )
    with path.open() as f:
        return json.load(f)


def _is_discharge_grounded(qa: dict) -> bool:
    """Return True if this QA pair can be answered from the discharge summary.

    Generated QA pairs (from Generation.generate_qa) include a `source_types`
    list. We only keep pairs where "discharge_summary" is one of the sources,
    because weak supervision (labeling chunks via token overlap with the answer)
    only works when the answer text appears somewhere in the discharge note.

    EHR-DS-QA pairs have no source_types field — they are always discharge-grounded
    by construction, so we keep all of them.
    """
    source_types = qa.get("source_types")
    if source_types is None:
        return True  # EHR-DS-QA: no field means always discharge-grounded
    return "discharge_summary" in source_types


# ── Event serialization ──────────────────────────────────────────────────────

def _fmt(val) -> str:
    """Format a value for text serialization, handling None / NaN."""
    if val is None:
        return ""
    if isinstance(val, float) and math.isnan(val):
        return ""
    return str(val).strip()


def _serialize_lab(ev: dict) -> str:
    ts    = _fmt(ev.get("timestamp"))
    label = _fmt(ev.get("label")) or "unknown"
    val   = _fmt(ev.get("value")) or _fmt(ev.get("valuenum"))
    unit  = _fmt(ev.get("unit"))
    flag  = _fmt(ev.get("flag"))
    line  = f"  {ts}  {label}: {val} {unit}".rstrip()
    if flag:
        line += f" [{flag}]"
    return line


def _serialize_medication(ev: dict) -> str:
    ts    = _fmt(ev.get("timestamp"))
    drug  = _fmt(ev.get("drug")) or "unknown"
    dose  = _fmt(ev.get("dose"))
    unit  = _fmt(ev.get("dose_unit"))
    route = _fmt(ev.get("route"))
    line  = f"  {ts}  {drug}"
    if dose:
        line += f" {dose} {unit}".rstrip()
    if route:
        line += f" ({route})"
    return line


def _serialize_vital(ev: dict) -> str:
    ts    = _fmt(ev.get("timestamp"))
    label = _fmt(ev.get("label")) or "unknown"
    val   = _fmt(ev.get("value")) or _fmt(ev.get("valuenum"))
    unit  = _fmt(ev.get("unit"))
    return f"  {ts}  {label}: {val} {unit}".rstrip()


def _serialize_procedure(ev: dict) -> str:
    ts    = _fmt(ev.get("timestamp"))
    title = _fmt(ev.get("title")) or _fmt(ev.get("icd_code"))
    return f"  {ts}  {title}".rstrip()


def _serialize_diagnosis(ev: dict) -> str:
    title = _fmt(ev.get("title")) or _fmt(ev.get("icd_code"))
    seq   = _fmt(ev.get("seq_num"))
    prefix = f"  {seq}." if seq else "  -"
    return f"{prefix} {title}"


def _serialize_generic(ev: dict) -> str:
    parts = []
    for k, v in ev.items():
        if k == "event_type":
            continue
        s = _fmt(v)
        if s:
            parts.append(f"{k}={s}")
    return "  " + ", ".join(parts)


_EVENT_SERIALIZERS = {
    "lab":        _serialize_lab,
    "medication": _serialize_medication,
    "vital":      _serialize_vital,
    "procedure":  _serialize_procedure,
    "diagnosis":  _serialize_diagnosis,
}

_EVENT_HEADERS = {
    "diagnosis":  "CLINICAL DIAGNOSES:",
    "lab":        "CLINICAL LABORATORY VALUES:",
    "vital":      "CLINICAL VITAL SIGNS:",
    "medication": "CLINICAL MEDICATIONS ADMINISTERED:",
    "procedure":  "CLINICAL PROCEDURES PERFORMED:",
}

_EVENT_ORDER = ["diagnosis", "lab", "vital", "medication", "procedure"]


def serialize_events(events: list[dict]) -> str:
    """Convert structured clinical events into readable text with section headers.

    The headers use ALL-CAPS format so the section-based chunker in chunker.py
    detects them and creates separate chunks per event type.
    """
    groups: dict[str, list[dict]] = {}
    for ev in events:
        etype = ev.get("event_type", "other")
        groups.setdefault(etype, []).append(ev)

    sections: list[str] = []

    for etype in _EVENT_ORDER:
        evts = groups.pop(etype, [])
        if not evts:
            continue
        header = _EVENT_HEADERS[etype]
        fmt    = _EVENT_SERIALIZERS[etype]
        lines  = [header] + [fmt(ev) for ev in evts]
        sections.append("\n".join(lines))

    for etype, evts in sorted(groups.items()):
        header = f"CLINICAL {etype.upper()}:"
        lines  = [header] + [_serialize_generic(ev) for ev in evts]
        sections.append("\n".join(lines))

    return "\n\n".join(sections)


# ── Merge ────────────────────────────────────────────────────────────────────

def merge(
    timelines: list[dict],
    qa_records: list[dict],
    include_events: bool = True,
) -> list[dict]:
    """Join timelines with QA pairs on (subject_id, hadm_id).

    Args:
        timelines:      Output of load_timelines().
        qa_records:     Output of load_qa_pairs().
        include_events: If True (default), note_text is the discharge summary
                        concatenated with serialized structured events.  All QA
                        pairs are kept because event values now appear in the
                        chunked text.  If False, only the discharge summary is
                        used and cross-source QA pairs are filtered out.

    Returns a list of dicts, one per matched admission:
        subject_id       int
        hadm_id          int
        note_text        str   — full patient text (discharge + events, or discharge only)
        qa_pairs         list  — [{question, answer, ...}, ...]
    """
    qa_index: dict[tuple[int, int], list[dict]] = {}
    dropped_cross_source = 0
    for rec in qa_records:
        key = (int(rec["subject_id"]), int(rec["hadm_id"]))
        all_pairs = rec.get("qa_pairs") or []
        if include_events:
            pairs = [qa for qa in all_pairs if qa.get("question") and qa.get("answer")]
        else:
            pairs = [
                qa for qa in all_pairs
                if qa.get("question") and qa.get("answer") and _is_discharge_grounded(qa)
            ]
            dropped_cross_source += len(all_pairs) - len(pairs)
        if pairs:
            qa_index[key] = pairs

    if dropped_cross_source > 0:
        print(
            f"Filtered out {dropped_cross_source} cross-source QA pairs "
            "(answers not in discharge summary — weak supervision inapplicable)"
        )

    merged: list[dict] = []
    skipped_no_qa   = 0
    skipped_no_note = 0

    for t in timelines:
        key = (int(t["subject_id"]), int(t["hadm_id"]))
        qa_pairs  = qa_index.get(key)
        discharge = (t.get("discharge_summary") or "").strip()

        if not qa_pairs:
            skipped_no_qa += 1
            continue
        if not discharge:
            skipped_no_note += 1
            continue

        if include_events:
            events_text = serialize_events(t.get("events") or [])
            note_text = discharge + "\n\n" + events_text if events_text else discharge
        else:
            note_text = discharge

        merged.append({
            "subject_id": int(t["subject_id"]),
            "hadm_id":    int(t["hadm_id"]),
            "note_text":  note_text,
            "qa_pairs":   qa_pairs,
        })

    print(
        f"Merged {len(merged)} records "
        f"(skipped {skipped_no_qa} with no QA, {skipped_no_note} with no note text)"
    )
    if include_events:
        print("  note_text = discharge summary + serialized structured events")
    else:
        print("  note_text = discharge summary only")
    return merged


def load_and_merge(
    timelines_path: str | Path = _DEFAULT_TIMELINES,
    qa_path:        str | Path = _DEFAULT_QA_JSON,
    include_events: bool = True,
) -> list[dict]:
    """Convenience wrapper: load both files and merge in one call."""
    timelines  = load_timelines(timelines_path)
    qa_records = load_qa_pairs(qa_path)
    return merge(timelines, qa_records, include_events=include_events)
